ulabox_ruler_expression_list:
    pattern: /list
    defaults: { _controller: ulabox_ruler.controller.expression:listAction }

ulabox_ruler_expression_create:
    pattern: /create
    defaults: { _controller: ulabox_ruler.controller.expression:createAction }

ulabox_ruler_expression_update:
    pattern: /{id}/update
    defaults: { _controller: ulabox_ruler.controller.expression:updateAction }

ulabox_ruler_expression_delete:
    pattern: /{id}/delete
    defaults: { _controller: ulabox_ruler.controller.expression:deleteAction }

ulabox_ruler_expression_duplicate:
    pattern: /{id}/duplicate
    defaults: { _controller: ulabox_ruler.controller.expression:duplicateAction }

ulabox_ruler_expression_show:
    pattern: /{id}
    defaults: { _controller: ulabox_ruler.controller.expression:showAction }